### ISSUE TITLE
The window size and program size of some software are different

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#11]
新的主题导致部分软件窗口尺寸与程序尺寸不一致，如截图、磁盘等

New theme causes window size and program size of some software to be different, such as screenshots, disks, etc.

**Comment by kwwzzz** [comment]
在最新黑色主题中已解决，等白色设计稿出来后会同步解决

**Comment by Liang-zy** [comment]
20200313版本测试未通过 。

**Comment by liumin0322** [comment]
20200328版本测试通过。
