### ISSUE TITLE
Screenshot software theme color matching problem

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#12]
截图软件的按钮颜色与字体太相近

The button color of the screenshot software is too close to the font

**Comment by kwwzzz** [comment]
最新黑色主题已解决，等白色设计稿出来后会同步解决

**Comment by 1216338727aa** [comment]
20200313版本测试通过。发现新问题，鼠标放在[截图S] 上无明显变化，高亮不明显。

**Comment by Liang-zy** [comment]
20200313版本测试未通过 。

**Comment by kwwzzz** [comment]
已解决

**Comment by liumin0322** [comment]
20200328版本测试通过。
