### ISSUE TITLE
使用键盘快捷键调节音量，屏幕显示的音量调节图标底色为一个大白板

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#17]
Use keyboard shortcuts to adjust the volume. The background of the volume adjustment icon displayed on the screen is a large white board.

**Comment by fenshezhuiyi** [comment]
不确定和主题是否有关系，需和开发人员确定是否有无将样式写死。如是主题原因，解决方法如下：
1、换图标
2、换样式

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
