### ISSUE TITLE
Taskbar icon sizes are inconsistent

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#21]
任务栏图标大小不一致

测试步骤：
1、任务栏设置为最小尺寸
2、添加10+款应用至快速启动栏
3、图标大小尺寸不一致

**Comment by fenshezhuiyi** [comment]
大小不一致主要从以下对比：
1、UKUI设计的图标
2、三方图标
3、和任务栏确认一下是读取的png还是svg，还是两者都有

**Comment by kwwzzz** [comment]
任务栏控制图标的显示 建议分给任务栏

**Comment by fenshezhuiyi** [comment]
任务栏已解

**Comment by Liang-zy** [comment]
20200528 test passed
