### ISSUE TITLE
缺少磁盘和打印机内部所需图标

### ISSUE THREAD

**Issue by ll-eleven** [ukui/ubuntukylin-theme#23]
在org.mate.interface的icon-theme设置为ukui-icon-theme-default时，运行磁盘或打印机会导致系统卡死；在设置为其他主题时，能正常运行。依据报错和警告，是这两程序缺少内部所缺图标

**Comment by kwwzzz** [comment]
已解决

**Comment by liumin0322** [comment]
20200309版本测试通过
