### ISSUE TITLE
窗口最大化状态下的“最大化”图标不正确

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#30]

**Comment by fenshezhuiyi** [comment]
测试一下图标，这个bug第一次遇到，有可能是配置文件设置而引起的问题

**Comment by Liang-zy** [comment]
默认打开窗口为纯黑色的主题的应用软件如：磁盘、截图、游戏等窗口最大化后，'最大化、最小化、关闭‘图标反而变小了，

**Comment by kwwzzz** [comment]
这个是由于gtk qt两套主题差异导致　gsetting值不统一　gtk调用gnome图标qt调用ukui-icon-theme-default 得等控制面板统一后可以解决

**Comment by kwwzzz** [comment]
已解决

**Comment by liumin0322** [comment]
20200328版本测试通过。
