### ISSUE TITLE
桌面设置为超大图标，tar格式的文件图标异常小

### ISSUE THREAD

**Issue by CrossCC** [ukui/ubuntukylin-theme#33]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：
1. 在桌面创建一个格式为tar的压缩包
2. 右键设置视图类型为超大图标

预期结果：所有图标显示正常。

实际结果：tar格式的压缩包显示异常小。

**Comment by liumin0322** [comment]
20200321版本测试通过。
