### ISSUE TITLE
深色主题，控制面板中仅二级菜单栏显示为黑框

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#35]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、通过终端切换为黑色主题
2、打开控制面板

预期结果：控制面板显示为深色主题样式

实际结果：控制面板中仅二级菜单栏显示为黑色块

**Comment by fenshezhuiyi** [comment]
原因：控制面板大部分样式是自我管理，已经和主题分离。后续稳定再进行整合。
