### ISSUE TITLE
whl格式文件，图标尺寸不一致

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#37]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、拷贝一个“xxx.whl”格式的文件至桌面
2、图标尺寸比桌面其他图标大
3、打开文件管理器，桌面目录，该图标比其他图标尺寸小

预期结果：图标尺寸一致

实际结果：在桌面比其他图标大，在文件管理器中比其他图标尺寸小

**Comment by fenshezhuiyi** [comment]
负责人从这两方面核实：如果是相差不大，可能是图标本身问题，如果相差的大，可能是缺图标。

**Comment by kwwzzz** [comment]
已解决

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
