### ISSUE TITLE
黑色主题的预览窗口，标题也显示为黑色

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#39]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开终端，查看任务栏预览窗口

预期结果：主题配色可清楚看到窗口标题

实际结果：窗口背景和文字均为黑色

**Comment by kwwzzz** [comment]
已解决

**Comment by kwwzzz** [comment]
这里由任务栏控制　主题暂时无法控制

**Comment by kwwzzz** [comment]
已解决

**Comment by liumin0322** [comment]
20200321版本测试通过。
