### ISSUE TITLE
任务栏快速启动栏中，应用图标排列不整齐

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#40]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、添加wps、控制面板、终端至快速启动栏

预期结果：排列整齐

实际结果：应用图标排列显示不整齐

**Comment by kwwzzz** [comment]
这个问题建议转给任务栏,主题无法控制图标相对于控件位置,只能显示对应图片

**Comment by kwwzzz** [comment]
已解决
