### ISSUE TITLE
系统默认主题是浅色模式，不是系统默认

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ubuntukylin-theme#50]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.安装完成进入系统
2.控制面板查看主题

预期结果： 主题应该为系统默认
实际结果： 默认主题时浅色模式，而不是系统默认

**Comment by fenshezhuiyi** [comment]
需要控制面板改，然后现在的默认主题名是：ukui-default，其他为ukui-light,ukui-dark

**Comment by fenshezhuiyi** [comment]
最终方案：还是为ukui-white(默认主题)，ukui-dark（深色主主题）
