### ISSUE TITLE
Rhyrhmbox 音量调节样式有问题

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ubuntukylin-theme#53]
![图片](https://user-images.githubusercontent.com/39893452/77536903-1d318f80-6ed8-11ea-9204-f3b6ba53d731.png)
![图片](https://user-images.githubusercontent.com/39893452/77537033-64b81b80-6ed8-11ea-88cd-20884280e66a.png)

**Comment by kwwzzz** [comment]
已解决

**Comment by Liang-zy** [comment]
20200402版本测试通过
