### ISSUE TITLE
不可选状态的置灰效果不明显

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#58]
![2020-03-26 16-00-07屏幕截图](https://user-images.githubusercontent.com/48200161/77623354-ef515700-6f7a-11ea-89fd-3a818eeb4654.png)

**Comment by Liang-zy** [comment]
20200402版本测试通过

**Comment by kwwzzz** [comment]
已解决

**Comment by Liang-zy** [comment]
The 20200410 version failed the test

**Comment by kwwzzz** [comment]
Solved

**Comment by Liang-zy** [comment]
20200521  test failed
![image](https://user-images.githubusercontent.com/39893452/82807769-051bc380-9ebb-11ea-9107-67ff760dea8d.png)

**Comment by kwwzzz** [comment]
solver

**Comment by Liang-zy** [comment]
20200611 test passed
