### ISSUE TITLE
磁盘工具中，各区域间无区域划分

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#59]
![2020-03-26 16-16-25屏幕截图](https://user-images.githubusercontent.com/48200161/77624815-5a9c2880-6f7d-11ea-8eef-5f9acf41212c.png)

**Comment by kwwzzz** [comment]
已解决

**Comment by 1216338727aa** [comment]
20200402版本测试通过

**Comment by liumin0322** [comment]
20200402-beta版本测试未通过，各区域模块间仍无划分

**Comment by kwwzzz** [comment]
已解决

**Comment by Liang-zy** [comment]
The 20200410 version passed the test
