### ISSUE TITLE
文本文档中，有的下拉菜单鼠标悬停的高亮效果为白色

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#62]
![2020-03-26 16-33-41屏幕截图](https://user-images.githubusercontent.com/48200161/77626070-b49ded80-6f7f-11ea-8597-2085914ffcbe.png)

**Comment by kwwzzz** [comment]
已解决

**Comment by Liang-zy** [comment]
20200402版本测试通过
