### ISSUE TITLE
【对对碰】下拉菜单中，所有选项均为高亮状态

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#63]
![2020-03-26 17-20-58屏幕截图](https://user-images.githubusercontent.com/48200161/77630613-4d376c00-6f86-11ea-9559-2a8b1d7d3dd1.png)

**Comment by kwwzzz** [comment]
已解决

**Comment by Liang-zy** [comment]
20200402版本测试通过
