### ISSUE TITLE
In the inactive window, some text cannot be recognized

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#76]
![2020-04-15 10-58-19屏幕截图](https://user-images.githubusercontent.com/48200161/79295183-a7cf4280-7f0a-11ea-8811-23594ba3b873.png)

**Comment by kwwzzz** [comment]
Solved

**Comment by Liang-zy** [comment]
20200521 test failed
![微信图片_20200525192708](https://user-images.githubusercontent.com/39893452/82809619-19fa5600-9ebf-11ea-8389-e80128316121.png)

**Comment by kwwzzz** [comment]
Solved

**Comment by Liang-zy** [comment]
20200528 test passed
