### ISSUE TITLE
Some icons are displayed differently in half-screen and full-screen modes

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#8]
开始菜单中，Mate终端、Mate系统监视器、Vim和语言支持图标，在半屏和全屏模式下，显示不一致

In the start menu, the Mate terminal, Mate system monitor, Vim and language support icons are displayed differently in half-screen and full-screen modes.

**Comment by kwwzzz** [comment]
已解决

**Comment by liumin0322** [comment]
20200309版本测试通过
