### ISSUE TITLE
GTK application theme not in effect

### ISSUE THREAD

**Issue by liumin0322** [ukui/ubuntukylin-theme#82]
gtk应用主题未生效
![截图-2020年5月16日 17时12分12秒](https://user-images.githubusercontent.com/48200161/82115911-685d7580-9798-11ea-8618-60f0cf08e9b8.png)

**Comment by kwwzzz** [comment]
由于ukui-setting-daemon没有正常工作导致

**Comment by fenshezhuiyi** [comment]
已确认，ukui-settings-daemon已默认起来，是gsettings默认还是kylin-black-theme，需要改成ukui-white。做版本时没拉新上传的这个包，然后需要刘亮下次做版本时集成这个包就可生效。

**Comment by fenshezhuiyi** [comment]
已生效
