### ISSUE TITLE
Network connection interface, place the mouse on the "down arrow" in front of Ethernet or WiFi, and find that the arrow disappears

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ubuntukylin-theme#87]
![2020-05-26 16-00-08屏幕截图](https://user-images.githubusercontent.com/39893452/82876162-ef65d700-9f6a-11ea-969b-2df516496a90.png)

**Comment by kwwzzz** [comment]
Solved

**Comment by Liang-zy** [comment]
20200528 test passed
